export const options = [
  {
    id: "chat",
    name: "Chat",
    description: "Open ended conversation with an AI assistant",
    options: {
      model: "text-davinci-003",
      temperature: 0.9,
      max_tokens: 150,
      top_p: 1,
      frequency_penalty: 0.0,
      presence_penalty: 0.6,
      stop: [" Human:", " AI:"],
    },
  },
  {
    id: "qa",
    name: "Q and A",
    description: "Answer questions based on existing knowledge",
    options: {
      model: "text-davinci-003",
      temperature: 0,
      max_tokens: 100,
      top_p: 1,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
      stop: ["\n"],
    },
  },
  {
    id: "grammar",
    name: "Grammar correction",
    description: "Corrects sentences into standard English",
    options: {
      model: "text-davinci-003",
      temperature: 0,
      max_tokens: 60,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    id: "summarize",
    name: "Summarize for a 2nd grader",
    description: "Translates difficult text into simpler concepts",
    options: {
      model: "text-davinci-003",
      temperature: 0.7,
      max_tokens: 64,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    id: "englishtoother",
    name: "English to other languages",
    description: "Translates English text into French, Spanish and Japanese",
    options: {
      model: "text-davinci-003",
      temperature: 0.3,
      max_tokens: 100,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    id: "pythontonatural",
    name: "Python to natural language",
    description: "Explain a piece of Python code in human readable language",
    options: {
      model: "code-davinci-002",
      temperature: 0,
      max_tokens: 64,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    id: "translatecode",
    name: "Translate programming languages",
    description: "Use the comments to specify the source and target languages",
    options: {
      model: "code-davinci-002",
      temperature: 0,
      max_tokens: 54,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
      stop: ["###"],
    },
  },
  {
    id: "explaincode",
    name: "Explain code",
    description: "Explain a complicated piece of code",
    options: {
      model: "code-davinci-002",
      temperature: 0,
      max_tokens: 64,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
      stop: ['"""'],
    },
  },
  {
    id: "sqlrequest",
    name: "SQL request",
    description: "Create simple SQL queries",
    options: {
      model: "text-davinci-003",
      temperature: 0.3,
      max_tokens: 60,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    id: "essayoutline",
    name: "Essay outline",
    description: "Generate an outline for a research topic",
    options: {
      model: "text-davinci-003",
      temperature: 0.3,
      max_tokens: 150,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
];
